# -*- coding: utf-8 -*-
"""Python Intro.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mWnGDlPl4jXV2yRPU4rIfTkO7V6lrqOG

# **Let's Begin With Printing Hello World**
"""

a = "Hello World"
print(a)

"""# **Now we do a for loop**"""

Surnames = ("Muthoni","Karmago","Njuguna","Omondi","Kibet","Kigen","Mutiso")

for name in Surnames:
  print(name)

"""# **Random numbers**"""

import random

# Generate a random integer between 1 and 10
random_number = random.randint(1, 10)
print(random_number)

# Generate a random floating-point number between 0 and 1
random_float = random.random()
print(random_float)

# Generate a random element from a list
my_list = ['Windows', 'Macios', 'Android']
random_element = random.choice(my_list)
print(random_element)

# Shuffle the elements in a list
random.shuffle(my_list)
print(my_list)

import random

# Generate a random integer between 1 and 50
random_number = random.randint(1, 50)
print(random_number)

# Generate a random floating-point number between 0 and 1
random_float = random.random()
print(random_float)

# Generate a random element from a list
thy_list = ['Ruiru', 'Ruaka', 'Ruai','Runda','Ruaraka','Lunga Lunga','Likoni','Ruro']
random_element = random.choice(thy_list)
print(random_element)

# Shuffle the elements in a list
random.shuffle(thy_list)
print(thy_list)

"""# **Let's take inputs from users**"""

name = input("What is your name?: ")

age = input("How old are you?: ")

print(f"Hello, my name is {name}, and I am {age} years old")

"""# **Let's play a game**"""

import random

secret_number = random.randint(1, 100)
num_guesses = 0

print("I'm thinking of a number between 1 and 100. Can you guess what it is?")

while True:
    guess = int(input("Enter your guess: "))
    num_guesses += 1

    if guess == secret_number:
        print(f"Congratulations, you guessed the number in {num_guesses} guesses!")
        break
    elif guess < secret_number:
        print("Too low! Try again.")
    else:
        print("Too high! Try again.")

"""# **How about we sell some tickets**"""

tickets = []

while True:
    print("\n1. Sell Ticket")
    print("2. Print All Tickets")
    print("3. Quit")

    choice = int(input("Enter your choice: "))

    if choice == 1:
        name = input("Enter the customer's name: ")
        num_tickets = int(input("Enter the number of tickets: "))

        ticket = {"name": name, "num_tickets": num_tickets}
        tickets.append(ticket)

        print(f"\nSold {num_tickets} tickets to {name}!")
    elif choice == 2:
        print("\nAll Tickets:")
        for ticket in tickets:
            print(f"{ticket['name']} - {ticket['num_tickets']} tickets")
    elif choice == 3:
        print("\nGoodbye!")
        break
    else:
        print("\nInvalid choice. Please try again.")

"""# **Its Time**"""

import time
import datetime

end_time = datetime.datetime.now() + datetime.timedelta(seconds=10)

while datetime.datetime.now() < end_time:
    time_left = end_time - datetime.datetime.now()
    print(f"Time left: {time_left.seconds} seconds", end="\r")
    time.sleep(1)

print("\nTime's up!")

"""# **When are we?**"""

import calendar

year = int(input("Enter the year: "))
month = int(input("Enter the month (1-12): "))

# Create a TextCalendar object
cal = calendar.TextCalendar()

# Format and print the calendar
print(cal.formatmonth(year, month))

"""# **Lottery Game**"""

import random

# Generate a list of 6 random numbers between 1 and 49
lottery_numbers = random.sample(range(1, 50), 6)

# Prompt the user to enter 6 numbers between 1 and 49
print("Welcome to the lottery! Please enter 6 numbers between 1 and 49.")
user_numbers = []
for i in range(6):
    while True:
        try:
            num = int(input(f"Enter number {i+1}: "))
            if num < 1 or num > 49:
                raise ValueError("Number must be between 1 and 49.")
            elif num in user_numbers:
                raise ValueError("Number already entered.")
            break
        except ValueError as e:
            print(e)
    user_numbers.append(num)

# Sort the user's numbers and the lottery numbers
user_numbers.sort()
lottery_numbers.sort()

# Print the user's numbers and the lottery numbers
print(f"\nYour numbers: {user_numbers}")
print(f"Lottery numbers: {lottery_numbers}")

# Check how many numbers match
matches = set(user_numbers).intersection(set(lottery_numbers))
num_matches = len(matches)

# Print the result
if num_matches == 6:
    print("\nCongratulations! You have won the jackpot!")
elif num_matches >= 3:
    print(f"\nYou have matched {num_matches} numbers and won a prize!")
else:
    print("\nHard Luck, you did not match any numbers. Please try again.")

"""# **A while loop**"""

i = 1
while i < 10:
    print(i)
    i += 1

"""# **Let's find the capital for you**"""

import random

countries = {
    "Afghanistan": "Kabul",
    "Albania": "Tirana",
    "Algeria": "Algiers",
    "Andorra": "Andorra la Vella",
    "Angola": "Luanda",
    "Kenya": "Nairobi",
    "United Kingdom": "London",
    "United States": "Washinton DC",
    "Egypt": "Cairo",
    "Nigeria": "Abuja"
}
# add more countries and capitals as desired

# get a random country and its capital
country, capital = random.choice(list(countries.items()))

print("What is the capital of", country + "?")
user_input = input()

if user_input.lower() == capital.lower():
    print("Correct!")
else:
    print("Sorry, the capital of", country, "is", capital + ".")

"""# **Creating Reservations**"""

tables = {
    "Table 1": False,
    "Table 2": False,
    "Table 3": False,
    "Table 4": False,
    "Table 5": False
}

while True:
    # display the available tables
    print("Available tables:")
    for table, available in tables.items():
        if not available:
            print(table)
    print()

    # prompt the user to choose a table
    table_choice = input("Choose a table (or 'q' to quit): ")
    if table_choice.lower() == "q":
        break

    # check if the chosen table is available
    if table_choice not in tables:
        print("Invalid choice.")
        continue
    elif tables[table_choice]:
        print("Sorry, that table is not available.")
        continue

    # reserve the chosen table
    tables[table_choice] = True
    print("Table", table_choice, "has been reserved.")

"""# **Counter**"""

counts = {}

while True:
    # prompt the user to enter an item
    item = input("Enter an item (or 'q' to quit): ")
    if item.lower() == "q":
        break

    # increment the count for the item
    if item in counts:
        counts[item] += 1
    else:
        counts[item] = 1

# display the counts for each item
print("Counts:")
for item, count in counts.items():
    print(item + ":", count)

"""# **Aptitude Test**"""

# define the questions and answers
questions = {
    "What is the capital of France?": "Paris",
    "What is the largest country in the world by land area?": "Russia",
    "What is the currency of Japan?": "Yen",
    "Who is the president of Kenya?": "William Ruto",
    "When did Covid-19 begin?": "January 2020",
    "Which is the largest ocean?": "Pacific",
    "How many countries does Africa has?": "Fifty four",
    "Kenyan staple food is?": "Ugali",
    "Is lesbainism legal in Kenya?": "No",
    "Which is the biggest company in East Africa": "Safaricom"
}

# keep track of the score
score = 0

# ask the questions
for question, answer in questions.items():
    print(question)
    user_answer = input("Your answer: ")
    if user_answer.lower() == answer.lower():
        print("Correct!")
        score += 1
    else:
        print("Incorrect. The correct answer is", answer)
    print()

# display the final score
print("Your score is", score, "out of", len(questions))

"""# **Truth or Dare**"""

import random

# define the truth and dare prompts
truth_prompts = [
    "What is your biggest fear?",
    "Have you ever lied to your best friend?",
    "What was the last thing you searched for on your phone?",
    "What is something you're embarrassed to admit you like?"
]

dare_prompts = [
    "Call your crush and confess your love to them (or a random number if you're single)",
    "Do 20 jumping jacks",
    "Send a funny meme to your entire contact list",
    "Sing a song in front of everyone"
]

# randomly select a truth or dare prompt
is_truth = random.choice([True, False])
prompt = random.choice(truth_prompts if is_truth else dare_prompts)

# prompt the user to answer the truth or complete the dare
if is_truth:
    print("Truth:", prompt)
    answer = input("Your answer: ")
    print("Thanks for being honest!")
else:
    print("Dare:", prompt)
    input("Press enter when you're ready...")
    print("Okay, here we go!")
    # implement the dare here

print("Thanks for playing!")

"""# **Days Countdown**"""

import datetime

# specify the target date
target_date = datetime.date(2023, 5, 31)

# get today's date
today = datetime.date.today()

# calculate the number of days until the target date
days_remaining = (target_date - today).days

# print the countdown message
print(f"Only {days_remaining} day(s) left until {target_date.strftime('%B %d, %Y')}!, Adios Guys, Its Been Real")

"""# **Young's Modulus**"""

import numpy as np

# input data
stress = np.array([100, 200, 300, 500, 700, 800, 1000, 1200,1500, 1800])   # stress in MPa
strain = np.array([0.001, 0.002, 0.003, 0.005, 0.007, 0.008, 0.01, 0.012, 0.015, 0.018])   # strain

# calculate Young's modulus
E = stress / strain

# print result
print(f"Young's modulus = {E.mean()} MPa")

"""# **Collatz**"""

def collatz(n):
    while n > 1:
        if n % 2 == 0:
            n = n // 2
        else:
            n = 3 * n + 1
    return n


def main():
    n = int(input("Enter a number: "))
    print("The Collatz sequence for", n, "is:")
    print(collatz(n))


if __name__ == "__main__":
    main()